### ISSUE TITLE
Moving node-report into core

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-report#110]
In the diagnostic summit the consensus was to move node-report into core (not as a module but fully integrated).

@richardlau we should set up a time to discuss and if possible document the timeline to do that.

**Comment by mhdawson** [comment]
I know this is open https://github.com/nodejs/node/pull/19661 but I believe that is to add it as a dependency.

**Comment by joyeecheung** [comment]
I believe during the diagnostics summit we were talking about exposing it via `util` because adding an additional module comes with more implications than putting it under an existing one. There is also the question of how it should be enabled in core, https://github.com/nodejs/node/pull/19661 currently enables it when there are fatal errors or `SIGUSR2` sent, but that might be conflicting with user land modules.

**Comment by richardlau** [comment]
https://github.com/nodejs/node/pull/22712 has been merged.
