### ISSUE TITLE
Please provide a way to remove or filter printed env vars

### ISSUE THREAD

**Issue by hulkish** [nodejs/node-report#114]
For example, currently all env vars are reported:
```sh
================================================================================
==== System Information ========================================================

Environment variables
  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  SOME_API_KEY=abc123
  ...etc
```

Per this example, `SOME_API_KEY` is actually considered sensitive and we don't want it printed to console. I think there should be a way to hide these.

**Comment by richardlau** [comment]
Relevant bit of code that currently reports the env vars:
https://github.com/nodejs/node-report/blob/824648730f85b7d434e55382c49f4eef55ce884f/src/node_report.cc#L851-L875

Some things to discuss:
- Should this be implemented as a blacklist (i.e. user lists the env vars to exclude) or a whitelist (i.e. user lists the env vars to include)?
- Should the excluded env vars be omitted entirely, or included with the value replaced, e.g. `SOME_API_KEY=[redacted]`?

**Comment by hulkish** [comment]
@richardlau how about:

```sh
// example 1:
NODE_REPORT_ENV_BLACKLIST=MY_API_KEY_1, MY_API_KEY_2
// example 2:
NODE_REPORT_ENV_WHITELIST=MY_API_URL_1, MY_API_URL_2
```

I think we just provide both options. Then, we jusr indicate that whitelist behavior will **override** blacklist behavior.

**Comment by sam-github** [comment]
The blacklist I understand, and printing it with some kind of replaced value makes sense to me, but what's the use case for the whitelist?

**Comment by sam-github** [comment]
I wasn't clear on how the white and black list interacted. As I understand you know, the black list will be completely ignored if a white list is present.

Points 1 and 3 above I don't think should be goals of node-report. node-report is verbose by design (I believe), it doesn't have a way to add/remove sections, or increase and decrease verbosity.

Point 2 I find mildly compelling. node-reports aren't public, people concerned about the report output can post-process them to remove anything they want somewhere between disk and whatever log storage they use. Still, white lists look easy to implement when only one of a white or black list has to be considered.

Are you interested in implementing this feature, or hoping someone else will?

**Comment by hulkish** [comment]
@sem-github i must admit, i am a green horn with c++ - however, if u can point me in right direction...id be happy to take a stab at it

**Comment by sam-github** [comment]
Richard pointed at the relevant code above. I guess you'd have to change it to get the env vars you propose, and check if the env var that is about to be printed is white or black listed.
