### ISSUE TITLE
Add lint rules from main nodejs project.

### ISSUE THREAD

**Issue by hhellyer** [nodejs/node-report#44]
Nodereport should have a lint target developers can run to check the source code formatting rather that having reviewers find the issues.
This would help prevent pull requests from being cluttered up with formatting changes and allow us to focus more on the technical discussions.

Since nodereport (node-report) is a project under Nodejs the rules should be copied over from there so the format is consistent with the main project.

**Comment by richardlau** [comment]
There was some previous discussion of this in #15.

https://github.com/nodejs/node uses eslint (with custom rules) for JavaScript and cpplint.py for C++ (majority of node(-)report is C++). We most definitely want to follow the same rules to reduce the barriers to entry for contributors and to smooth future integration of this project with the runtime. 

For JavaScript, @geek offered a PR (https://github.com/nodejs/nodereport/pull/15#issuecomment-258564766) but this was raised against my [fork of nodereport](https://github.com/richardlau/nodereport/pull/1) instead of this repository. 

n.b. https://github.com/nodejs/node-inspect did something similar (https://github.com/nodejs/node-inspect/commit/d669dc593f5ad5ca7a48f19f0905ef66ec0e540d)

**Comment by richardlau** [comment]
We currently have #45 and #46 as two different approaches to linting the JavaScript source, but neither of them add the custom eslint rules in https://github.com/nodejs/node/tree/master/tools/eslint-rules. Do we need those?

**Comment by mhdawson** [comment]
I think the rules we apply should be exactly the same as applied to node core.

**Comment by geek** [comment]
@mhdawson I updated node-style to be exactly those applied to node core. It was missing the custom node-core rules before, those are now included.

**Comment by Fishrock123** [comment]
> Since nodereport (node-report) is a project under Nodejs the rules should be copied over from there so the format is consistent with the main project.

Please do not copy core's styles. They exist in that specific form only for legacy reasons.

**Comment by cjihrig** [comment]
I also think that we should stick to the rules used by core.

**Comment by mhdawson** [comment]
Went ahead and approved https://github.com/nodejs/node-report/pull/45#pullrequestreview-19205886

**Comment by gibfahn** [comment]
@Fishrock123 could you be more specific about which rules you think shouldn't be followed?
